/*
 * This file is generated by jOOQ.
*/
package com.yz.springmvc.pojo.tables;


import com.yz.springmvc.pojo.Keys;
import com.yz.springmvc.pojo.Wallpaper;
import com.yz.springmvc.pojo.tables.records.WallpaperCategoryRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WallpaperCategory extends TableImpl<WallpaperCategoryRecord> {

    private static final long serialVersionUID = 251189808;

    /**
     * The reference instance of <code>wallpaper.wallpaper_category</code>
     */
    public static final WallpaperCategory WALLPAPER_CATEGORY = new WallpaperCategory();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WallpaperCategoryRecord> getRecordType() {
        return WallpaperCategoryRecord.class;
    }

    /**
     * The column <code>wallpaper.wallpaper_category.id</code>.
     */
    public final TableField<WallpaperCategoryRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>wallpaper.wallpaper_category.wallpaper_id</code>.
     */
    public final TableField<WallpaperCategoryRecord, String> WALLPAPER_ID = createField("wallpaper_id", org.jooq.impl.SQLDataType.VARCHAR.length(60), this, "");

    /**
     * The column <code>wallpaper.wallpaper_category.category_id</code>.
     */
    public final TableField<WallpaperCategoryRecord, Integer> CATEGORY_ID = createField("category_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>wallpaper.wallpaper_category</code> table reference
     */
    public WallpaperCategory() {
        this("wallpaper_category", null);
    }

    /**
     * Create an aliased <code>wallpaper.wallpaper_category</code> table reference
     */
    public WallpaperCategory(String alias) {
        this(alias, WALLPAPER_CATEGORY);
    }

    private WallpaperCategory(String alias, Table<WallpaperCategoryRecord> aliased) {
        this(alias, aliased, null);
    }

    private WallpaperCategory(String alias, Table<WallpaperCategoryRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Wallpaper.WALLPAPER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<WallpaperCategoryRecord, Integer> getIdentity() {
        return Keys.IDENTITY_WALLPAPER_CATEGORY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<WallpaperCategoryRecord> getPrimaryKey() {
        return Keys.KEY_WALLPAPER_CATEGORY_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<WallpaperCategoryRecord>> getKeys() {
        return Arrays.<UniqueKey<WallpaperCategoryRecord>>asList(Keys.KEY_WALLPAPER_CATEGORY_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WallpaperCategory as(String alias) {
        return new WallpaperCategory(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public WallpaperCategory rename(String name) {
        return new WallpaperCategory(name, null);
    }
}
