/*
 * This file is generated by jOOQ.
*/
package com.yz.springmvc.pojo.tables;


import com.yz.springmvc.pojo.Keys;
import com.yz.springmvc.pojo.tables.records.WallpaperRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Wallpaper extends TableImpl<WallpaperRecord> {

    private static final long serialVersionUID = -2018520151;

    /**
     * The reference instance of <code>wallpaper.wallpaper</code>
     */
    public static final Wallpaper WALLPAPER_ = new Wallpaper();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WallpaperRecord> getRecordType() {
        return WallpaperRecord.class;
    }

    /**
     * The column <code>wallpaper.wallpaper.id</code>.
     */
    public final TableField<WallpaperRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR.length(60).nullable(false), this, "");

    /**
     * The column <code>wallpaper.wallpaper.thumb_url</code>.
     */
    public final TableField<WallpaperRecord, String> THUMB_URL = createField("thumb_url", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>wallpaper.wallpaper.img_url</code>.
     */
    public final TableField<WallpaperRecord, String> IMG_URL = createField("img_url", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>wallpaper.wallpaper.preview_url</code>.
     */
    public final TableField<WallpaperRecord, String> PREVIEW_URL = createField("preview_url", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>wallpaper.wallpaper.tag</code>.
     */
    public final TableField<WallpaperRecord, Integer> TAG = createField("tag", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("2", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * Create a <code>wallpaper.wallpaper</code> table reference
     */
    public Wallpaper() {
        this("wallpaper", null);
    }

    /**
     * Create an aliased <code>wallpaper.wallpaper</code> table reference
     */
    public Wallpaper(String alias) {
        this(alias, WALLPAPER_);
    }

    private Wallpaper(String alias, Table<WallpaperRecord> aliased) {
        this(alias, aliased, null);
    }

    private Wallpaper(String alias, Table<WallpaperRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return com.yz.springmvc.pojo.Wallpaper.WALLPAPER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<WallpaperRecord> getPrimaryKey() {
        return Keys.KEY_WALLPAPER_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<WallpaperRecord>> getKeys() {
        return Arrays.<UniqueKey<WallpaperRecord>>asList(Keys.KEY_WALLPAPER_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Wallpaper as(String alias) {
        return new Wallpaper(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Wallpaper rename(String name) {
        return new Wallpaper(name, null);
    }
}
