/*
 * This file is generated by jOOQ.
*/
package com.yz.springmvc.pojo;


import com.yz.springmvc.pojo.tables.Category;
import com.yz.springmvc.pojo.tables.Wallpaper;
import com.yz.springmvc.pojo.tables.WallpaperCategory;
import com.yz.springmvc.pojo.tables.records.CategoryRecord;
import com.yz.springmvc.pojo.tables.records.WallpaperCategoryRecord;
import com.yz.springmvc.pojo.tables.records.WallpaperRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>wallpaper</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<WallpaperCategoryRecord, Integer> IDENTITY_WALLPAPER_CATEGORY = Identities0.IDENTITY_WALLPAPER_CATEGORY;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CategoryRecord> KEY_CATEGORY_PRIMARY = UniqueKeys0.KEY_CATEGORY_PRIMARY;
    public static final UniqueKey<WallpaperRecord> KEY_WALLPAPER_PRIMARY = UniqueKeys0.KEY_WALLPAPER_PRIMARY;
    public static final UniqueKey<WallpaperCategoryRecord> KEY_WALLPAPER_CATEGORY_PRIMARY = UniqueKeys0.KEY_WALLPAPER_CATEGORY_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<WallpaperCategoryRecord, Integer> IDENTITY_WALLPAPER_CATEGORY = createIdentity(WallpaperCategory.WALLPAPER_CATEGORY, WallpaperCategory.WALLPAPER_CATEGORY.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<CategoryRecord> KEY_CATEGORY_PRIMARY = createUniqueKey(Category.CATEGORY, "KEY_category_PRIMARY", Category.CATEGORY.ID);
        public static final UniqueKey<WallpaperRecord> KEY_WALLPAPER_PRIMARY = createUniqueKey(Wallpaper.WALLPAPER_, "KEY_wallpaper_PRIMARY", Wallpaper.WALLPAPER_.ID);
        public static final UniqueKey<WallpaperCategoryRecord> KEY_WALLPAPER_CATEGORY_PRIMARY = createUniqueKey(WallpaperCategory.WALLPAPER_CATEGORY, "KEY_wallpaper_category_PRIMARY", WallpaperCategory.WALLPAPER_CATEGORY.ID);
    }
}
