/*
 * This file is generated by jOOQ.
*/
package com.yz.springmvc.pojo;


import com.yz.springmvc.pojo.tables.Category;
import com.yz.springmvc.pojo.tables.Wallpaper;
import com.yz.springmvc.pojo.tables.WallpaperCategory;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in wallpaper
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>wallpaper.category</code>.
     */
    public static final Category CATEGORY = com.yz.springmvc.pojo.tables.Category.CATEGORY;

    /**
     * The table <code>wallpaper.wallpaper</code>.
     */
    public static final Wallpaper WALLPAPER_ = com.yz.springmvc.pojo.tables.Wallpaper.WALLPAPER_;

    /**
     * The table <code>wallpaper.wallpaper_category</code>.
     */
    public static final WallpaperCategory WALLPAPER_CATEGORY = com.yz.springmvc.pojo.tables.WallpaperCategory.WALLPAPER_CATEGORY;
}
