/*
 * This file is generated by jOOQ.
*/
package com.yz.springmvc.pojo.tables.records;


import com.yz.springmvc.pojo.tables.Wallpaper;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WallpaperRecord extends UpdatableRecordImpl<WallpaperRecord> implements Record5<String, String, String, String, Integer> {

    private static final long serialVersionUID = 1612724268;

    /**
     * Setter for <code>wallpaper.wallpaper.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>wallpaper.wallpaper.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>wallpaper.wallpaper.thumb_url</code>.
     */
    public void setThumbUrl(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>wallpaper.wallpaper.thumb_url</code>.
     */
    public String getThumbUrl() {
        return (String) get(1);
    }

    /**
     * Setter for <code>wallpaper.wallpaper.img_url</code>.
     */
    public void setImgUrl(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>wallpaper.wallpaper.img_url</code>.
     */
    public String getImgUrl() {
        return (String) get(2);
    }

    /**
     * Setter for <code>wallpaper.wallpaper.preview_url</code>.
     */
    public void setPreviewUrl(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>wallpaper.wallpaper.preview_url</code>.
     */
    public String getPreviewUrl() {
        return (String) get(3);
    }

    /**
     * Setter for <code>wallpaper.wallpaper.tag</code>.
     */
    public void setTag(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>wallpaper.wallpaper.tag</code>.
     */
    public Integer getTag() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, String, String, String, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, String, String, String, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Wallpaper.WALLPAPER_.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Wallpaper.WALLPAPER_.THUMB_URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Wallpaper.WALLPAPER_.IMG_URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Wallpaper.WALLPAPER_.PREVIEW_URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Wallpaper.WALLPAPER_.TAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getThumbUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getImgUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getPreviewUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getTag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WallpaperRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WallpaperRecord value2(String value) {
        setThumbUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WallpaperRecord value3(String value) {
        setImgUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WallpaperRecord value4(String value) {
        setPreviewUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WallpaperRecord value5(Integer value) {
        setTag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WallpaperRecord values(String value1, String value2, String value3, String value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WallpaperRecord
     */
    public WallpaperRecord() {
        super(Wallpaper.WALLPAPER_);
    }

    /**
     * Create a detached, initialised WallpaperRecord
     */
    public WallpaperRecord(String id, String thumbUrl, String imgUrl, String previewUrl, Integer tag) {
        super(Wallpaper.WALLPAPER_);

        set(0, id);
        set(1, thumbUrl);
        set(2, imgUrl);
        set(3, previewUrl);
        set(4, tag);
    }
}
